NAME_MAP = {
    # Upgrade or unit renames
    "zerglingmovementspeed": "Metabolic Boost",
    "zerglingattackspeed": "Adrenal Glands",
    "overlordspeed": "Carapace",
    "glialreconstitution": "Glial Reconstitution",
    "tunnelingclaws": "Tunneling Claws",
    "burrow": "Burrow",
    "centrifugalhooks": "Centrifugal Hooks",
    "centrificalhooks": "centrifugal hooks",
    "combatshield": "Combat Shield",
    "stimpack": "Stimpack",
    "barrackstechlab": "Tech Lab on Barracks",
    "barracks tech lab": "Tech Lab on Barracks",
    "barracksreactor": "Reactor on Barracks",
    "barracks reactor": "Reactor on Barracks",
    "factorytechlab": "Tech Lab on Factory",
    "factory tech lab": "Tech Lab on Factory",
    "factoryreactor": "Reactor on Factory",
    "factory reactor": "Reactor on Factory",
    "starporttechlab": "Tech Lab on Starport",
    "starport tech lab": "Tech Lab on Starport",
    "starportreactor": "Reactor on Starport",
    "starport reactor": "Reactor on Starport",
    # Additional mappings from unusual names
    "shieldwall": "Combat Shield",
    "punishergrenades": "Concussive Shells",
    "cyclonelockondamageupgrade": "Mag-Field Accelerator",
    "personalcloaking": "Cloak",
    "bansheespeed": "Hyperflight Rotors",
    "medivacincreasespeedboost": "Rapid Reignition System",
    "ravencorvidreactor": "Corvid Reactor",
    "ravenrecalibratedexplosives": "Recalibrated Explosives",
    "ravenenhancedmunitions": "Enhanced Munitions",
    "drillclaws": "Drilling Claws",
    "diggingclaws": "adaptive talons",
    "hisecautotracking": "Hi-Sec Auto Tracking",
    "battlecruiserenablespecializations": "Weapon Refit",
    "terranneosteelarmor": "Neosteel Armor",
    "liberatoragrangeupgrade": "Advanced Ballistics",
    "highcapacitybarrels": "Infernal Pre-Igniter",
    "smartservos": "Smart Servos",
    "medivac caduceus reactor": "Caduceus Reactor",
    "frenzy": "Nanomuscular swell",
    "lurker den m p": "lurker den",
    "scv": "SCV",
    "s c v": "SCV",
    "zerg ground armor level1": "carapace",
    "zerg ground armor level2": "carapace",
    "zerg ground armor level3": "carapace",
    "zerggroundarmorlevel1": "carapace",
    "zerggroundarmorlevel2": "carapace",
    "zerggroundarmorlevel3": "carapace",
    "vikingfighter": "Viking",
    "viking fighter": "Viking",
    "vikingassault": "Viking",
    "viking assault": "Viking",
    # Protoss upgrades
    "templar archive": "Templar Archives",
    "templararchives": "Templar Archives",
    "psi storm tech": "psionic storm",
    "psistormtech": "psionic storm",
    "blink tech": "blink",
    "blinktech": "blink",
    "dark templar blink upgrade": "shadow stride",
    "darktemplarblinkupgrade": "shadow stride",
    "observer gravitic booster": "gravitic boosters",
    "observergraviticbooster": "gravitic boosters",
    "adept piercing attack": "resonating glaives",
    "adeptpiercingattack": "resonating glaives",
    "anion pulse-crystals upgrade": "Anion pulse-crystals",
    "anionpulsecrystalsupgrade": "Anion pulse-crystals",
    "warpgatewarpgateresearch": "Warp gatewarp gate",
    "warp gatewarp gate research": "Warp gatewarp gate",
    "void ray speed upgrade": "flux vanes",
    "voidrayspeedupgrade": "flux vanes",
    "tempest ground attack upgrade": "tectonic destabilizers",
    "tempestgroundattackupgrade": "tectonic destabilizers",
}
