NAME_MAP = {
    # Upgrade or unit renames
    "zerglingmovementspeed": "Metabolic Boost",
    "zerglingattackspeed": "Adrenal Glands",
    "overlordspeed": "Carapace",
    "glialreconstitution": "Glial Reconstitution",
    "tunnelingclaws": "Tunneling Claws",
    "burrow": "Burrow",
    "centrifugalhooks": "Centrifugal Hooks",
    "centrificalhooks": "centrifugal hooks",
    "combatshield": "Combat Shield",
    "stimpack": "Stimpack",
    # Additional mappings from unusual names
    "shieldwall": "Combat Shield",
    "punishergrenades": "Concussive Shells",
    "cyclonelockondamageupgrade": "Mag-Field Accelerator",
    "personalcloaking": "Cloak",
    "bansheespeed": "Hyperflight Rotors",
    "medivacincreasespeedboost": "Rapid Reignition System",
    "ravencorvidreactor": "Corvid Reactor",
    "ravenrecalibratedexplosives": "Recalibrated Explosives",
    "ravenenhancedmunitions": "Enhanced Munitions",
    "drillclaws": "Drilling Claws",
    "diggingclaws": "adaptive talons",
    "hisecautotracking": "Hi-Sec Auto Tracking",
    "battlecruiserenablespecializations": "Weapon Refit",
    "terranneosteelarmor": "Neosteel Armor",
    "liberatoragrangeupgrade": "Advanced Ballistics",
    "highcapacitybarrels": "Infernal Pre-Igniter",
    "smartservos": "Smart Servos",
    "frenzy": "Nanomuscular swell",
    "lurker den m p": "lurker den",
    "scv": "SCV",
    "s c v": "SCV",
}
